### ISSUE TITLE
Encore: Lightweight Measurement of Web Censorship with Cross-Origin Requests (Oct 26)

### ISSUE THREAD

**Issue by ryscheng** [UWNetworksLab/CSE590L#1]
http://conferences.sigcomm.org/sigcomm/2015/pdf/papers/p653.pdf

**Comment by willscott** [comment]
+1. This is a good paper that I'm familiar with. I won't be back by Oct 26th, but could potentially attend remotely.

**Comment by AnnaKornfeldSimpson** [comment]
I was going to suggest this one. Happy to help lead.

**Comment by nkrsharma** [comment]
Yes, this one is interesting. I'd like to attend.

**Comment by plvines** [comment]
+1

**Comment by scrivener** [comment]
Interested.
