### ISSUE TITLE
Analyzing the Performance of an Anycast CDN (Dec 14?)

### ISSUE THREAD

**Issue by willscott** [UWNetworksLab/CSE590L#10]
Matt Calder from USC is up at Microsoft this fall and expressed interest in stopping by to talk about his recent IMC talk:
http://nsl.cs.usc.edu/~mcalder/AnycastCDN.pdf

I need to confirm he can make this date, but it seems like an appropriate talk for 590l.

**Comment by AnnaKornfeldSimpson** [comment]
Would attend. (Are people still in town?)

**Comment by nkrsharma** [comment]
Would attend.

**Comment by ryscheng** [comment]
Would attend

**Comment by willscott** [comment]
Matt tentatively confirms he can make this date
