### ISSUE TITLE
Twitter Heron: Stream Processing at Scale (Visit by Karthik, Nov 16)

### ISSUE THREAD

**Issue by bholt** [UWNetworksLab/CSE590L#11]
Karthik is visiting Seattle and would be willing to present on Twitter's new streaming platform, Heron (Storm v2).

SIGMOD paper from this year: http://dl.acm.org/citation.cfm?id=2742788

**Comment by bholt** [comment]
@AnnaKornfeldSimpson suggested I propose this for 590L since there isn't anything scheduled for Nov 16 yet.

**Comment by AnnaKornfeldSimpson** [comment]
would attend.

**Comment by nkrsharma** [comment]
Yupp, would attend. We can schedule it during this slot.

**Comment by bholt** [comment]
There is some preference for a 3:30pm time. Does that work for the 590L folks?

**Comment by nkrsharma** [comment]
Yupp, works for me.

**Comment by ryscheng** [comment]
Interested in seeing talk, but 3:30pm is a conflict for me. Is the speaker unable to make 1:30pm?

**Comment by bholt** [comment]
Nope, 1:30 should be fine I think. Just a preference on the part of some Sampa people. I will go ahead and schedule this then. Thanks, all!
