### ISSUE TITLE
HotNets Lightning Talks Day 1 (Feb 22)

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [UWNetworksLab/CSE590L#14]
Please pick a paper from HotNets http://conferences.sigcomm.org/hotnets/2015/program.html and put together max 4 slides about it. We'll aim for 4 papers on the 22nd and the rest on March 7 (link for overflow list: https://github.com/UWNetworksLab/CSE590L/issues/17)

I'll do: http://conferences.sigcomm.org/hotnets/2015/papers/yu.pdf which proposes IoT security via middleboxes.

**Comment by ryscheng** [comment]
+1

**Comment by ryscheng** [comment]
SpaceHub: A Smart Relay System for Smart Home
http://conferences.sigcomm.org/hotnets/2015/papers/meng.pdf

**Comment by nkrsharma** [comment]
I'll do : Time's Forgotten: Using NTP to understand Internet Latency

http://conferences.sigcomm.org/hotnets/2015/papers/durairajan.pdf

**Comment by FreakyPenguin** [comment]
High Speed Networks Need Proactive Congestion Control
http://conferences.sigcomm.org/hotnets/2015/papers/jose.pdf
