### ISSUE TITLE
cMix: Anonymization by High-Performance Scalable Mixing (Feb 29)

### ISSUE THREAD

**Issue by ryscheng** [UWNetworksLab/CSE590L#16]
https://eprint.iacr.org/2016/008.pdf

This is the paper we briefly mentioned by David Chaum at the end of the Herd discussion today

**Comment by AnnaKornfeldSimpson** [comment]
Would attend. As would probably many other people in the security lab - we
were discussing this in lab meeting today.

2016-01-11 17:10 GMT-08:00 Raymond Cheng <notifications@github.com>:
