### ISSUE TITLE
Herd: A Scalable, Traffic Analysis Resistant Anonymity Network for VoIP Systems (Jan 11)

### ISSUE THREAD

**Issue by ryscheng** [UWNetworksLab/CSE590L#2]
http://conferences.sigcomm.org/sigcomm/2015/pdf/papers/p639.pdf

**Comment by AnnaKornfeldSimpson** [comment]
Interested/willing to help lead, but not voting for this one over the Encore paper.

**Comment by plvines** [comment]
+1. Willing to help lead

**Comment by scrivener** [comment]
Interested.

**Comment by ryscheng** [comment]
Awesome! Is there a date that works for both @AnnaKornfeldSimpson and @plvines?

**Comment by nkrsharma** [comment]
interested.

**Comment by ryscheng** [comment]
Looks like this has 5 attendees. How about 11/23?

**Comment by AnnaKornfeldSimpson** [comment]
Security lab has student meeting with guest speaker on 11/23 at 1:30 so
that won't work.

**Comment by ryscheng** [comment]
Oh right. How about 11/30?

**Comment by AnnaKornfeldSimpson** [comment]
11/30 works for me, as long as I don't have to make the slides (traveling until the night before). @plvines does this work for you?

**Comment by plvines** [comment]
Yeah, that should be okay

**Comment by AnnaKornfeldSimpson** [comment]
Moving this to sometime next quarter due to Security Lab meeting conflict. Sorry for the delay!

**Comment by plvines** [comment]
Moved to January 11th.

**Comment by ryscheng** [comment]
Great discussion today!
