### ISSUE TITLE
Alibi Routing (Nov 9)

### ISSUE THREAD

**Issue by ryscheng** [UWNetworksLab/CSE590L#3]
http://conferences.sigcomm.org/sigcomm/2015/pdf/papers/p611.pdf

**Comment by AnnaKornfeldSimpson** [comment]
Interested/willing to help lead, but not voting for this one over the Encore paper.

**Comment by plvines** [comment]
+0.5. Looks interesting but potentially not that deeply interesting

**Comment by scrivener** [comment]
Yeah, I'm interested in this.

**Comment by ryscheng** [comment]
Awesome! Is there a date that works for both @scrivener and @AnnaKornfeldSimpson?

**Comment by scrivener** [comment]
@AnnaKornfeldSimpson Does the 19th or the 26th work for you?

**Comment by AnnaKornfeldSimpson** [comment]
If you mean this month, I think we have papers for those (mcTLS and Encore)? Unless we want to do this instead of mcTLS on the 19th - I don't have a strong preference, @plvines probably has .5 of one

**Comment by scrivener** [comment]
I don't think I understand the system, I was assuming the dates proposed higher on the thread were propsed dates. Maybe someone who understands the system can propose dates?


(I'm out of town today, btw.)




A

**Comment by AnnaKornfeldSimpson** [comment]
Let's do Nov 2 if that works for @ryscheng and @plvines

**Comment by plvines** [comment]
I don't know what paper we're talking about buy I believe Nov 2nd should
work unless unknown events happen

Thanks,
-Paul

**Comment by ryscheng** [comment]
Can we do Nov 9 or Nov 16 instead?

**Comment by AnnaKornfeldSimpson** [comment]
Prefer Nov 9.  @plvines The paper in the title of the issue...
