### ISSUE TITLE
Analyzing Protocol Implementations for Interoperability (Dec 7)

### ISSUE THREAD

**Issue by colin-scott** [UWNetworksLab/CSE590L#4]
https://www.usenix.org/conference/nsdi15/technical-sessions/presentation/pedrosa

**Comment by AnnaKornfeldSimpson** [comment]
Sounds interesting, would attend.

**Comment by scrivener** [comment]
Would attend.

**Comment by nkrsharma** [comment]
Would attend.

**Comment by danyangz** [comment]
wound attend.

**Comment by AnnaKornfeldSimpson** [comment]
We've got plenty of attends - anyone willing to help lead? (commit to read the full paper)

**Comment by colin-scott** [comment]
I can lead this paper

**Comment by AnnaKornfeldSimpson** [comment]
@colin-scott @danyangz @nkrsharma The security lab's having a guest speaker on the 23rd and wants to have a student meeting at 1:30, which means me and @scrivener would have a conflict. Is there any chance we could move this to a different date?  Available dates are 11/16, 12/2 and 12/9.  Sorry about the mixup!

**Comment by colin-scott** [comment]
Do you mean 12/7?

I can't do 11/16 or 12/2, but 12/7 might work.

**Comment by AnnaKornfeldSimpson** [comment]
WHoops sorry off on my math.  Can everyone else do 12/7?

**Comment by danyangz** [comment]
I think I can do 12/7.

**Comment by nkrsharma** [comment]
I'll be out of town on 12/7, but I'm fine with missing this.

**Comment by AnnaKornfeldSimpson** [comment]
@scrivener Also confirmed 12/7 ok, so we're moving this to 12/7. Security lab logistics very much appreciate your flexibility!
