### ISSUE TITLE
Multi-Context TLS (mcTLS): Enabling Secure In-Network Functionality in TLS (Oct 19)

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [UWNetworksLab/CSE590L#5]
http://conferences.sigcomm.org/sigcomm/2015/pdf/papers/p199.pdf

Date moved due to midterm. Not sure if affiliates stuff conflicts on 19th? If not, prefer that.

**Comment by ryscheng** [comment]
Would attend. Looks interesting

**Comment by plvines** [comment]
+1 would help lead. Gone on October 12th

**Comment by scrivener** [comment]
Interested as well.

**Comment by AnnaKornfeldSimpson** [comment]
Confirming this for Oct 19 (aka Monday).
