### ISSUE TITLE
Central Control Over Distributed Routing (Feb 8)

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [UWNetworksLab/CSE590L#6]
http://conferences.sigcomm.org/sigcomm/2015/pdf/papers/p43.pdf

SIGCOMM 2015 Best Paper

(Unless we read this already? It looks familiar.)

**Comment by nkrsharma** [comment]
Sounds interesting.. Would attend.

**Comment by danyangz** [comment]
Will attend.

**Comment by AnnaKornfeldSimpson** [comment]
Naveen and Antoine will lead on Feb 8.
