### ISSUE TITLE
E2: A Framework for NFV Applications (Nov 2)

### ISSUE THREAD

**Issue by nkrsharma** [UWNetworksLab/CSE590L#7]
http://sigops.org/sosp/sosp15/current/2015-Monterey/printable/174-palkar.pdf

This is one of the only networks related work at this years SOSP. Sylvia gave a very nice talk, and it might be worth reading it.

**Comment by nkrsharma** [comment]
I am willing to lead.

**Comment by AnnaKornfeldSimpson** [comment]
Would attend. Sounds interesting!

**Comment by danyangz** [comment]
Will attend. Also can help lead.

**Comment by colin-scott** [comment]
Would attend, depending on the date

**Comment by AnnaKornfeldSimpson** [comment]
We were going to do next week (Nov 2) - does that work for you?

**Comment by AnnaKornfeldSimpson** [comment]
We were going to do next week (Nov 2) - does that work for you?

**Comment by colin-scott** [comment]
Yup!
