### ISSUE TITLE
Vuvuzela: Scalable Private Messaging Resistant to Traffic Analysis

### ISSUE THREAD

**Issue by nkrsharma** [UWNetworksLab/CSE590L#8]
http://sigops.org/sosp/sosp15/current/2015-Monterey/printable/136-hooff.pdf

Another interesting work at SOSP. I liked the talk, although there were a lot of questions about the system.

**Comment by nkrsharma** [comment]
Willing to lead.

**Comment by AnnaKornfeldSimpson** [comment]
Paul and I are doing this in 590s at the end of the quarter.

**Comment by nkrsharma** [comment]
Whoops, did not notice that.
