### ISSUE TITLE
Scalable Error Isolation for Distributed Systems

### ISSUE THREAD

**Issue by danyangz** [UWNetworksLab/CSE590L#9]
https://www.usenix.org/system/files/conference/nsdi15/nsdi15-paper-behrens.pdf

**Comment by AnnaKornfeldSimpson** [comment]
Would attend.

**Comment by colin-scott** [comment]
Would attend

**Comment by ryscheng** [comment]
Danyang, would you like to propose a date?

**Comment by danyangz** [comment]
I am taking a class that is in conflict with 590L this quarter. I am happy to present this next quarter. Or feel free to discuss this without me.
